### ISSUE TITLE
drush versions

### ISSUE THREAD

**Issue by joe-niland** [devpanel/serverlink#15]
Hi @vmmello

I noticed that the version of drush installed doesn't work with Drupal 8. Could we have the corresponding version of drush installed depending on the Drupal version?

**Comment by vmmello** [comment]
Actually this was a problem with the seed app of Drupal 8, it was not drush. I've updated that broken packaged Drupal 8.

Both drush 7 and drush 8 are installed on the servers, and just by running **drush** it automatically detects the best drush version for the Drupal version on the vhost.
